package com.qingqing.protodemo.protoresources.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent_account_permission_proto.proto

public final class AgentAccountPermissionProto {
  private AgentAccountPermissionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AgentPermissionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AgentPermissionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string agent_account_id = 2;</code>
     * @return The agentAccountId.
     */
    String getAgentAccountId();
    /**
     * <code>string agent_account_id = 2;</code>
     * @return The bytes for agentAccountId.
     */
    com.google.protobuf.ByteString
        getAgentAccountIdBytes();
  }
  /**
   * Protobuf type {@code AgentPermissionInfo}
   */
  public  static final class AgentPermissionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AgentPermissionInfo)
      AgentPermissionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AgentPermissionInfo.newBuilder() to construct.
    private AgentPermissionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentPermissionInfo() {
      id_ = "";
      agentAccountId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AgentPermissionInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AgentPermissionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              agentAccountId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentAccountPermissionProto.internal_static_AgentPermissionInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentAccountPermissionProto.internal_static_AgentPermissionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentPermissionInfo.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGENT_ACCOUNT_ID_FIELD_NUMBER = 2;
    private volatile Object agentAccountId_;
    /**
     * <code>string agent_account_id = 2;</code>
     * @return The agentAccountId.
     */
    public String getAgentAccountId() {
      Object ref = agentAccountId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        agentAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string agent_account_id = 2;</code>
     * @return The bytes for agentAccountId.
     */
    public com.google.protobuf.ByteString
        getAgentAccountIdBytes() {
      Object ref = agentAccountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        agentAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getAgentAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, agentAccountId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getAgentAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, agentAccountId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentPermissionInfo)) {
        return super.equals(obj);
      }
      AgentPermissionInfo other = (AgentPermissionInfo) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getAgentAccountId()
          .equals(other.getAgentAccountId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + AGENT_ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentAccountId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentPermissionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentPermissionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentPermissionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentPermissionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentPermissionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentPermissionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentPermissionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentPermissionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentPermissionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentPermissionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentPermissionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentPermissionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentPermissionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AgentPermissionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AgentPermissionInfo)
        AgentPermissionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentAccountPermissionProto.internal_static_AgentPermissionInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentAccountPermissionProto.internal_static_AgentPermissionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentPermissionInfo.class, Builder.class);
      }

      // Construct using AgentAccountPermissionProto.AgentPermissionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        agentAccountId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentAccountPermissionProto.internal_static_AgentPermissionInfo_descriptor;
      }

      @Override
      public AgentPermissionInfo getDefaultInstanceForType() {
        return AgentPermissionInfo.getDefaultInstance();
      }

      @Override
      public AgentPermissionInfo build() {
        AgentPermissionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AgentPermissionInfo buildPartial() {
        AgentPermissionInfo result = new AgentPermissionInfo(this);
        result.id_ = id_;
        result.agentAccountId_ = agentAccountId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentPermissionInfo) {
          return mergeFrom((AgentPermissionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentPermissionInfo other) {
        if (other == AgentPermissionInfo.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getAgentAccountId().isEmpty()) {
          agentAccountId_ = other.agentAccountId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentPermissionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentPermissionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object agentAccountId_ = "";
      /**
       * <code>string agent_account_id = 2;</code>
       * @return The agentAccountId.
       */
      public String getAgentAccountId() {
        Object ref = agentAccountId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          agentAccountId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string agent_account_id = 2;</code>
       * @return The bytes for agentAccountId.
       */
      public com.google.protobuf.ByteString
          getAgentAccountIdBytes() {
        Object ref = agentAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          agentAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string agent_account_id = 2;</code>
       * @param value The agentAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setAgentAccountId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        agentAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string agent_account_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentAccountId() {
        
        agentAccountId_ = getDefaultInstance().getAgentAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string agent_account_id = 2;</code>
       * @param value The bytes for agentAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setAgentAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        agentAccountId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AgentPermissionInfo)
    }

    // @@protoc_insertion_point(class_scope:AgentPermissionInfo)
    private static final AgentPermissionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentPermissionInfo();
    }

    public static AgentPermissionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AgentPermissionInfo>
        PARSER = new com.google.protobuf.AbstractParser<AgentPermissionInfo>() {
      @Override
      public AgentPermissionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgentPermissionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentPermissionInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AgentPermissionInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public AgentPermissionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListAgentAccountPermissionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListAgentAccountPermissionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code ListAgentAccountPermissionRequest}
   */
  public  static final class ListAgentAccountPermissionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListAgentAccountPermissionRequest)
      ListAgentAccountPermissionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListAgentAccountPermissionRequest.newBuilder() to construct.
    private ListAgentAccountPermissionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListAgentAccountPermissionRequest() {
      id_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListAgentAccountPermissionRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListAgentAccountPermissionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListAgentAccountPermissionRequest.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ListAgentAccountPermissionRequest)) {
        return super.equals(obj);
      }
      ListAgentAccountPermissionRequest other = (ListAgentAccountPermissionRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ListAgentAccountPermissionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListAgentAccountPermissionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ListAgentAccountPermissionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListAgentAccountPermissionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListAgentAccountPermissionRequest)
        ListAgentAccountPermissionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListAgentAccountPermissionRequest.class, Builder.class);
      }

      // Construct using AgentAccountPermissionProto.ListAgentAccountPermissionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionRequest_descriptor;
      }

      @Override
      public ListAgentAccountPermissionRequest getDefaultInstanceForType() {
        return ListAgentAccountPermissionRequest.getDefaultInstance();
      }

      @Override
      public ListAgentAccountPermissionRequest build() {
        ListAgentAccountPermissionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ListAgentAccountPermissionRequest buildPartial() {
        ListAgentAccountPermissionRequest result = new ListAgentAccountPermissionRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListAgentAccountPermissionRequest) {
          return mergeFrom((ListAgentAccountPermissionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListAgentAccountPermissionRequest other) {
        if (other == ListAgentAccountPermissionRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ListAgentAccountPermissionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ListAgentAccountPermissionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListAgentAccountPermissionRequest)
    }

    // @@protoc_insertion_point(class_scope:ListAgentAccountPermissionRequest)
    private static final ListAgentAccountPermissionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ListAgentAccountPermissionRequest();
    }

    public static ListAgentAccountPermissionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListAgentAccountPermissionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListAgentAccountPermissionRequest>() {
      @Override
      public ListAgentAccountPermissionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListAgentAccountPermissionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListAgentAccountPermissionRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ListAgentAccountPermissionRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ListAgentAccountPermissionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListAgentAccountPermissionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListAgentAccountPermissionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    java.util.List<AgentPermissionInfo>
        getPermissionInfoList();
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    AgentPermissionInfo getPermissionInfo(int index);
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    int getPermissionInfoCount();
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    java.util.List<? extends AgentPermissionInfoOrBuilder>
        getPermissionInfoOrBuilderList();
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    AgentPermissionInfoOrBuilder getPermissionInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ListAgentAccountPermissionResponse}
   */
  public  static final class ListAgentAccountPermissionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListAgentAccountPermissionResponse)
      ListAgentAccountPermissionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListAgentAccountPermissionResponse.newBuilder() to construct.
    private ListAgentAccountPermissionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListAgentAccountPermissionResponse() {
      permissionInfo_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListAgentAccountPermissionResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListAgentAccountPermissionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                permissionInfo_ = new java.util.ArrayList<AgentPermissionInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              permissionInfo_.add(
                  input.readMessage(AgentPermissionInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          permissionInfo_ = java.util.Collections.unmodifiableList(permissionInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListAgentAccountPermissionResponse.class, Builder.class);
    }

    public static final int PERMISSIONINFO_FIELD_NUMBER = 1;
    private java.util.List<AgentPermissionInfo> permissionInfo_;
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    public java.util.List<AgentPermissionInfo> getPermissionInfoList() {
      return permissionInfo_;
    }
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    public java.util.List<? extends AgentPermissionInfoOrBuilder>
        getPermissionInfoOrBuilderList() {
      return permissionInfo_;
    }
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    public int getPermissionInfoCount() {
      return permissionInfo_.size();
    }
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    public AgentPermissionInfo getPermissionInfo(int index) {
      return permissionInfo_.get(index);
    }
    /**
     * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
     */
    public AgentPermissionInfoOrBuilder getPermissionInfoOrBuilder(
        int index) {
      return permissionInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < permissionInfo_.size(); i++) {
        output.writeMessage(1, permissionInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < permissionInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, permissionInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ListAgentAccountPermissionResponse)) {
        return super.equals(obj);
      }
      ListAgentAccountPermissionResponse other = (ListAgentAccountPermissionResponse) obj;

      if (!getPermissionInfoList()
          .equals(other.getPermissionInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPermissionInfoCount() > 0) {
        hash = (37 * hash) + PERMISSIONINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ListAgentAccountPermissionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListAgentAccountPermissionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListAgentAccountPermissionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListAgentAccountPermissionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ListAgentAccountPermissionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListAgentAccountPermissionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListAgentAccountPermissionResponse)
        ListAgentAccountPermissionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListAgentAccountPermissionResponse.class, Builder.class);
      }

      // Construct using AgentAccountPermissionProto.ListAgentAccountPermissionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPermissionInfoFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (permissionInfoBuilder_ == null) {
          permissionInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          permissionInfoBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentAccountPermissionProto.internal_static_ListAgentAccountPermissionResponse_descriptor;
      }

      @Override
      public ListAgentAccountPermissionResponse getDefaultInstanceForType() {
        return ListAgentAccountPermissionResponse.getDefaultInstance();
      }

      @Override
      public ListAgentAccountPermissionResponse build() {
        ListAgentAccountPermissionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ListAgentAccountPermissionResponse buildPartial() {
        ListAgentAccountPermissionResponse result = new ListAgentAccountPermissionResponse(this);
        int from_bitField0_ = bitField0_;
        if (permissionInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            permissionInfo_ = java.util.Collections.unmodifiableList(permissionInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.permissionInfo_ = permissionInfo_;
        } else {
          result.permissionInfo_ = permissionInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListAgentAccountPermissionResponse) {
          return mergeFrom((ListAgentAccountPermissionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListAgentAccountPermissionResponse other) {
        if (other == ListAgentAccountPermissionResponse.getDefaultInstance()) return this;
        if (permissionInfoBuilder_ == null) {
          if (!other.permissionInfo_.isEmpty()) {
            if (permissionInfo_.isEmpty()) {
              permissionInfo_ = other.permissionInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePermissionInfoIsMutable();
              permissionInfo_.addAll(other.permissionInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.permissionInfo_.isEmpty()) {
            if (permissionInfoBuilder_.isEmpty()) {
              permissionInfoBuilder_.dispose();
              permissionInfoBuilder_ = null;
              permissionInfo_ = other.permissionInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              permissionInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPermissionInfoFieldBuilder() : null;
            } else {
              permissionInfoBuilder_.addAllMessages(other.permissionInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ListAgentAccountPermissionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ListAgentAccountPermissionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AgentPermissionInfo> permissionInfo_ =
        java.util.Collections.emptyList();
      private void ensurePermissionInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          permissionInfo_ = new java.util.ArrayList<AgentPermissionInfo>(permissionInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AgentPermissionInfo, AgentPermissionInfo.Builder, AgentPermissionInfoOrBuilder> permissionInfoBuilder_;

      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public java.util.List<AgentPermissionInfo> getPermissionInfoList() {
        if (permissionInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(permissionInfo_);
        } else {
          return permissionInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public int getPermissionInfoCount() {
        if (permissionInfoBuilder_ == null) {
          return permissionInfo_.size();
        } else {
          return permissionInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public AgentPermissionInfo getPermissionInfo(int index) {
        if (permissionInfoBuilder_ == null) {
          return permissionInfo_.get(index);
        } else {
          return permissionInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder setPermissionInfo(
          int index, AgentPermissionInfo value) {
        if (permissionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionInfoIsMutable();
          permissionInfo_.set(index, value);
          onChanged();
        } else {
          permissionInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder setPermissionInfo(
          int index, AgentPermissionInfo.Builder builderForValue) {
        if (permissionInfoBuilder_ == null) {
          ensurePermissionInfoIsMutable();
          permissionInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          permissionInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder addPermissionInfo(AgentPermissionInfo value) {
        if (permissionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionInfoIsMutable();
          permissionInfo_.add(value);
          onChanged();
        } else {
          permissionInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder addPermissionInfo(
          int index, AgentPermissionInfo value) {
        if (permissionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionInfoIsMutable();
          permissionInfo_.add(index, value);
          onChanged();
        } else {
          permissionInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder addPermissionInfo(
          AgentPermissionInfo.Builder builderForValue) {
        if (permissionInfoBuilder_ == null) {
          ensurePermissionInfoIsMutable();
          permissionInfo_.add(builderForValue.build());
          onChanged();
        } else {
          permissionInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder addPermissionInfo(
          int index, AgentPermissionInfo.Builder builderForValue) {
        if (permissionInfoBuilder_ == null) {
          ensurePermissionInfoIsMutable();
          permissionInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          permissionInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder addAllPermissionInfo(
          Iterable<? extends AgentPermissionInfo> values) {
        if (permissionInfoBuilder_ == null) {
          ensurePermissionInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, permissionInfo_);
          onChanged();
        } else {
          permissionInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder clearPermissionInfo() {
        if (permissionInfoBuilder_ == null) {
          permissionInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          permissionInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public Builder removePermissionInfo(int index) {
        if (permissionInfoBuilder_ == null) {
          ensurePermissionInfoIsMutable();
          permissionInfo_.remove(index);
          onChanged();
        } else {
          permissionInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public AgentPermissionInfo.Builder getPermissionInfoBuilder(
          int index) {
        return getPermissionInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public AgentPermissionInfoOrBuilder getPermissionInfoOrBuilder(
          int index) {
        if (permissionInfoBuilder_ == null) {
          return permissionInfo_.get(index);  } else {
          return permissionInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public java.util.List<? extends AgentPermissionInfoOrBuilder>
           getPermissionInfoOrBuilderList() {
        if (permissionInfoBuilder_ != null) {
          return permissionInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(permissionInfo_);
        }
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public AgentPermissionInfo.Builder addPermissionInfoBuilder() {
        return getPermissionInfoFieldBuilder().addBuilder(
            AgentPermissionInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public AgentPermissionInfo.Builder addPermissionInfoBuilder(
          int index) {
        return getPermissionInfoFieldBuilder().addBuilder(
            index, AgentPermissionInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AgentPermissionInfo permissionInfo = 1;</code>
       */
      public java.util.List<AgentPermissionInfo.Builder>
           getPermissionInfoBuilderList() {
        return getPermissionInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AgentPermissionInfo, AgentPermissionInfo.Builder, AgentPermissionInfoOrBuilder>
          getPermissionInfoFieldBuilder() {
        if (permissionInfoBuilder_ == null) {
          permissionInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AgentPermissionInfo, AgentPermissionInfo.Builder, AgentPermissionInfoOrBuilder>(
                  permissionInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          permissionInfo_ = null;
        }
        return permissionInfoBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListAgentAccountPermissionResponse)
    }

    // @@protoc_insertion_point(class_scope:ListAgentAccountPermissionResponse)
    private static final ListAgentAccountPermissionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ListAgentAccountPermissionResponse();
    }

    public static ListAgentAccountPermissionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListAgentAccountPermissionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListAgentAccountPermissionResponse>() {
      @Override
      public ListAgentAccountPermissionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListAgentAccountPermissionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListAgentAccountPermissionResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ListAgentAccountPermissionResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ListAgentAccountPermissionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AgentPermissionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AgentPermissionInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListAgentAccountPermissionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListAgentAccountPermissionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListAgentAccountPermissionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListAgentAccountPermissionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$agent_account_permission_proto.proto\";" +
      "\n\023AgentPermissionInfo\022\n\n\002id\030\001 \001(\t\022\030\n\020age" +
      "nt_account_id\030\002 \001(\t\"/\n!ListAgentAccountP" +
      "ermissionRequest\022\n\n\002id\030\001 \001(\t\"R\n\"ListAgen" +
      "tAccountPermissionResponse\022,\n\016permission" +
      "Info\030\001 \003(\0132\024.AgentPermissionInfoB\037\n\000B\033Ag" +
      "entAccountPermissionProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AgentPermissionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AgentPermissionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AgentPermissionInfo_descriptor,
        new String[] { "Id", "AgentAccountId", });
    internal_static_ListAgentAccountPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListAgentAccountPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListAgentAccountPermissionRequest_descriptor,
        new String[] { "Id", });
    internal_static_ListAgentAccountPermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListAgentAccountPermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListAgentAccountPermissionResponse_descriptor,
        new String[] { "PermissionInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
